/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.datit.view;

import com.datit.model.Budget;
import com.datit.model.User;
import com.datit.dao.BudgetDAO;
import com.datit.excel.WriteFileExcel;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DatIT
 */
public class BudgetManagement extends javax.swing.JFrame {

    /**
     * Creates new form BudgetManagement
     */
    private List<Budget> budgets;
    private BudgetDAO bgDao;
    private User currentUser;
    private List<Budget> bgInTable;
    //Table

    public BudgetManagement(User us) {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon.png")));
        currentUser = us;
        lb_name.setText("Welcome " + us.getName());
        bgDao = new BudgetDAO();
        //set data into form
        setDataInComboBox();
        initOrUpdateData();

    }

    private void setDataTotalIncomePay() {
        double total = 0;
        double income = 0;
        double pay = 0;
        for (Budget budget : budgets) {
            if (budget.getStatus()) {
                income += budget.getValues();
            } else {
                pay += budget.getValues();
            }
        }
        total = income - pay;
        txt_total.setText(total + "");
        txt_income.setText(income + "");
        txt_pay.setText(pay + "");
    }

    private void initOrUpdateData() {
        getDataFromDB();
        bindDataIntTable(budgets);
        setDataTotalIncomePay();
    }

    private void setDataInComboBox() {
        int month = LocalDate.now().getMonthValue();
        int year = LocalDate.now().getYear();
        cbx_month.setSelectedItem(month + "");
        cbx_year.setSelectedItem(year + "");
    }

    private void getDataFromDB() {
        int month = Integer.parseInt((String) cbx_month.getSelectedItem());
        int year = Integer.parseInt((String) cbx_year.getSelectedItem());
        budgets = bgDao.selectBudgetAll(currentUser, month, year);
    }

    private void bindDataIntTable(List<Budget> lst) {
        bgInTable = lst;
        String[] header = {"Id", "Title", "Create day", "Value", "Status"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        for (Budget budget : lst) {
            Vector v = new Vector();
            v.add(budget.getId());
            v.add(budget.getTitle());
            v.add(budget.getCreateDate());
            v.add(budget.getValues());
            v.add(budget.getStatus() ? "Income" : "Pay");
            model.addRow(v);
        }
        modelTable.setModel(model);

    }

    private boolean checkedIdSelected() {
        String id = txt_idSelected.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Select one row in table, Please", "Notification",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txt_idSelected = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_pay = new javax.swing.JTextField();
        txt_income = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbx_type = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbx_month = new javax.swing.JComboBox<>();
        cbx_year = new javax.swing.JComboBox<>();
        cbx_sort = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_del1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget App by [DatIT]");

        jPanel1.setBackground(new java.awt.Color(72, 201, 176));

        jPanel2.setBackground(new java.awt.Color(118, 215, 196));

        modelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        modelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modelTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(modelTable);

        jButton2.setBackground(new java.awt.Color(255, 195, 0));
        jButton2.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jButton2.setText("Reload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(255, 195, 0));
        btn_update.setFont(new java.awt.Font("Be Vietnam Pro", 0, 12)); // NOI18N
        btn_update.setText("UD");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_del.setBackground(new java.awt.Color(255, 195, 0));
        btn_del.setFont(new java.awt.Font("Be Vietnam Pro", 0, 12)); // NOI18N
        btn_del.setText("DEL");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Be Vietnam Pro", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID SEL");

        txt_total.setEditable(false);

        txt_pay.setEditable(false);

        txt_income.setEditable(false);
        txt_income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_incomeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Be Vietnam Pro", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INCOME");

        jLabel9.setFont(new java.awt.Font("Be Vietnam Pro", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PAY");

        jLabel10.setFont(new java.awt.Font("Be Vietnam Pro", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_idSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addComponent(txt_income, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(39, 39, 39)
                        .addComponent(txt_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txt_idSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update)
                    .addComponent(btn_del)
                    .addComponent(jLabel3)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txt_income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Be Vietnam Pro", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("By DatIT");

        cbx_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "INCOME", "PAY" }));
        cbx_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_typeItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Be Vietnam Pro", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FILTER");

        cbx_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "11", "12" }));
        cbx_month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_monthItemStateChanged(evt);
            }
        });

        cbx_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025" }));
        cbx_year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_yearItemStateChanged(evt);
            }
        });

        cbx_sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L -> H", "H -> L" }));
        cbx_sort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_sortItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Be Vietnam Pro", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SORT BY");

        jButton1.setBackground(new java.awt.Color(255, 195, 0));
        jButton1.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Be Vietnam Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WRITE FILE");

        lb_name.setFont(new java.awt.Font("Be Vietnam Pro", 2, 18)); // NOI18N
        lb_name.setForeground(new java.awt.Color(255, 255, 255));
        lb_name.setText("Welcome ");

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Budget App");

        jLabel6.setFont(new java.awt.Font("Be Vietnam Pro", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DATE");

        btn_del1.setBackground(new java.awt.Color(255, 195, 0));
        btn_del1.setFont(new java.awt.Font("Be Vietnam Pro", 0, 12)); // NOI18N
        btn_del1.setText("WR");
        btn_del1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbx_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGap(12, 12, 12)
                                .addComponent(cbx_month, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbx_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_del1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbx_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(lb_name)))))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jLabel7)
                    .addContainerGap(600, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lb_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_del1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbx_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel7)
                    .addContainerGap(547, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EditBudgetForm editForm = new EditBudgetForm(currentUser);
        editForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        initOrUpdateData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if (checkedIdSelected()) {
            long idSelect = Long.parseLong(txt_idSelected.getText());
            EditBudgetForm editForm = new EditBudgetForm(idSelect, currentUser);
            editForm.setVisible(true);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        if (checkedIdSelected()) {
            long idSelected = Long.parseLong(txt_idSelected.getText());
            int reply = JOptionPane.showConfirmDialog(null,
                    "Do you what delete title have Id [" + idSelected + "] ?",
                    "Delete Confirm",
                    JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                if (bgDao.deleteBudget(idSelected)) {
                    JOptionPane.showMessageDialog(null, "Delete Success", "Notification",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Delete Fail", "Notification",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void txt_incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_incomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_incomeActionPerformed

    private void modelTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelTableMousePressed
        // TODO add your handling code here:
        String valueId = String.valueOf(modelTable.getValueAt(modelTable.getSelectedRow(), 0));
        txt_idSelected.setText(valueId);
    }//GEN-LAST:event_modelTableMousePressed

    private void cbx_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_typeItemStateChanged
        // TODO add your handling code here:
        List<Budget> filterBg = new ArrayList<Budget>();
        String type_name = String.valueOf(cbx_type.getSelectedItem());
        if (!type_name.equals("ALL")) {
            boolean type = type_name.equals("INCOME");
            for (Budget budget : budgets) {
                if (budget.getStatus() == type) {
                    filterBg.add(budget);
                }
            }
            bindDataIntTable(filterBg);
        } else
            bindDataIntTable(budgets);
    }//GEN-LAST:event_cbx_typeItemStateChanged

    private void cbx_sortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_sortItemStateChanged
        // TODO add your handling code here:
        List<Budget> sortBg = bgInTable;
        String sort_request = String.valueOf(cbx_sort.getSelectedItem());
        if (sort_request.equals("L -> H")) {
            Collections.sort(sortBg);
        } else {
            Collections.sort(sortBg, Collections.reverseOrder());
        }
        bindDataIntTable(sortBg);

    }//GEN-LAST:event_cbx_sortItemStateChanged

    private void cbx_monthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_monthItemStateChanged
        // TODO add your handling code here:
        getDataFromDB();
        bindDataIntTable(budgets);
    }//GEN-LAST:event_cbx_monthItemStateChanged

    private void cbx_yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_yearItemStateChanged
        // TODO add your handling code here:
        getDataFromDB();
        bindDataIntTable(budgets);
    }//GEN-LAST:event_cbx_yearItemStateChanged

    private void btn_del1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        if (fc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            String path = fc.getSelectedFile().getPath();
            WriteFileExcel.WriteFile(path, bgInTable);
        }
    }//GEN-LAST:event_btn_del1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_del1;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbx_month;
    private javax.swing.JComboBox<String> cbx_sort;
    private javax.swing.JComboBox<String> cbx_type;
    private javax.swing.JComboBox<String> cbx_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_name;
    private javax.swing.JTable modelTable;
    private javax.swing.JTextField txt_idSelected;
    private javax.swing.JTextField txt_income;
    private javax.swing.JTextField txt_pay;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
