/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.datit.view;

import com.datit.model.User;
import com.datit.dao.UserDAO;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author DatIT
 */
public class SignInForm extends javax.swing.JFrame {

    /**
     * Creates new form SignInForm
     */
    private UserDAO usDao;

    public SignInForm() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon.png")));
        usDao = new UserDAO();
    }

    private boolean checkConstraint() {
        boolean success = false;
        String pass = String.valueOf(txt_pass.getPassword());
        String confirm = String.valueOf(txt_confirmpas.getPassword());
        if (txt_name.getText().equals("") || txt_username.getText().equals("")) {
            lb_notify.setText("Full name or username not empty !");
            return success;
        }
        if (!pass.equals(confirm) || pass.equals("")) {
            lb_notify.setText("Confirm pass not equal Password !");
            return success;
        }
        success = true;
        return success;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pn_singin = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        txt_confirmpas = new javax.swing.JPasswordField();
        lb_notify = new javax.swing.JLabel();
        btn_singin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In - Budget App");
        setBackground(new java.awt.Color(19, 141, 117));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(19, 141, 117));

        pn_singin.setBackground(new java.awt.Color(118, 215, 196));
        pn_singin.setPreferredSize(new java.awt.Dimension(296, 302));

        txt_name.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N

        txt_username.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 195, 0));
        jLabel1.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel1.setText("Full Name");

        jLabel2.setBackground(new java.awt.Color(255, 195, 0));
        jLabel2.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(255, 195, 0));
        jLabel3.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setBackground(new java.awt.Color(255, 195, 0));
        jLabel4.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        jLabel4.setText("Confirm Password");

        txt_pass.setEchoChar('\u25cf');
        txt_pass.setFocusAccelerator('\u25cf');

        txt_confirmpas.setEchoChar('\u25cf');
        txt_confirmpas.setFocusAccelerator('\u25cf');

        lb_notify.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pn_singinLayout = new javax.swing.GroupLayout(pn_singin);
        pn_singin.setLayout(pn_singinLayout);
        pn_singinLayout.setHorizontalGroup(
            pn_singinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_singinLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pn_singinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_notify, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_singinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(txt_username)
                        .addComponent(txt_confirmpas)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pn_singinLayout.setVerticalGroup(
            pn_singinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_singinLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_confirmpas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_notify, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_singin.setBackground(new java.awt.Color(218, 247, 166));
        btn_singin.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        btn_singin.setText("Sign In");
        btn_singin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_singinActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SIGN IN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btn_singin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(pn_singin, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(pn_singin, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_singin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_singinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_singinActionPerformed
        // TODO add your handling code here:
        if (checkConstraint()) {
            String name = txt_name.getText();
            String username = txt_username.getText();
            String pass = String.valueOf(txt_pass.getPassword());
            User us = new User(username, pass, name);
            if (usDao.insertUser(us)) {
                JOptionPane.showMessageDialog(null, "Sign In Success");
                this.dispose();
            } else {
                lb_notify.setText("Change username !!!");
            }
        }
    }//GEN-LAST:event_btn_singinActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_singin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_notify;
    private javax.swing.JPanel pn_singin;
    private javax.swing.JPasswordField txt_confirmpas;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
